
outdir: /DATA/usr/c.leemans/projects/tagmap_ruben/cl20200121_hopping_mathias
input_dir: '/DATA/usr/m.eder/Tn5_tagmentation/E919_SB_PB_primer_test'

META_INFO: /DATA/usr/c.leemans/projects/tagmap_ruben/ME21012020_for_Christ_sequencing_data.txt

mingap: 100


mapper_options: "--very-sensitive"
bowtie_index:
    mm10: "/DATA/usr/c.leemans/data/mm10/index/bowtie2/mm10_1-19_XYM"
    hg38: "/DATA/usr/c.leemans/data/mm10/index/bowtie2/mm10_1-19_XYM"

## minimum mapping quality for a read
min_mapq_read: 0
## minimum for the maximum mapping quality of reads belonging to one putative insertion
min_max_mapq: 2

## minimum for the mean mapping quality of all reads belonging to one putative insertion
min_avg_mapq: 0

max_pair_dist: 15000000

min_depth: 5

structure:
    For_SB: |
        ID      5'             3' type                       req     second-read pos   keep-bases
        r2      AGTGAGTTTAAATGTATTTGGCTAAGGTGTATGTAAACTTCCGACTTCAACTGTA -  const  present  True  var  2
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   -  False var -
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -        True var -
    Rev_SB: |
        ID      5'    3' type    req     second-read pos   keep-bases
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   - False var -
        r2      AAACGAGTTTTAATGACTCCAACTTAAGTGTATGTAAACTTCCGACTTCAACTGTA  -  const   present True  var 2
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -       True var -
    For_PB: |
        ID      5'             3' type                       req     second-read pos   keep-bases
        r2      GTACGTCACAATATGATTATCTTTCTAGGGTTAA -  const  present  True  -  4
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   -  False var -
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -        True var -
        r2_rev  -  TTAACCCTAGAAAGATAATCATAT  const           -        False var -
    Rev_PB: |
        ID      5'    3' type    req     second-read pos   keep-bases
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   - False var -
        r2_rev  -  TTAACCCTAGAAAGATAGTCTGCGTAAAATTG  const   -       False var -
        r2      CAATTTTACGCAGACTATCTTTCTAGGGTTAA  -  const   present True  - 4
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -       True var -

samtools: samtools
mapper: bowtie2
parser: ~t.v.schaik/mydata/modules/read-parsing/read_parser.py
