
outdir: /DATA/usr/c.leemans/projects/tagmap_ruben/cl20191210_hopping_mathias
input_dir: /shared/gcf/m.eder/5776/fastq_files

META_INFO: /DATA/usr/c.leemans/projects/tagmap_ruben/cl20191210_hopping_metadata.txt

mingap: 100


mapper_options: "--very-sensitive"
bowtie_index:
    mm10: "/DATA/usr/c.leemans/data/mm10/index/bowtie2/mm10_1-19_XYM"

## minimum mapping quality for a read
min_mapq_read: 0
## minimum for the maximum mapping quality of reads belonging to one putative insertion
min_max_mapq: 2

## minimum for the mean mapping quality of all reads belonging to one putative insertion
min_avg_mapq: 0

max_pair_dist: 15000000

min_depth: 5



structure:
    For: |
        ID      5'             3' type                       req     second-read pos   keep-bases
        r2      AGTGAGTTTAAATGTATTTGGCTAAGGTGTATGTAAACTTCCGACTTCAACTGTA -  const  present  True  var  2
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   -  False var -
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -        True var -
    Rev: |
        ID      5'    3' type    req     second-read pos   keep-bases
        r1      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   - False var -
        r2      AAACGAGTTTTAATGACTCCAACTTAAGTGTATGTAAACTTCCGACTTCAACTGTA  -  const   present True  var 2
        r1_rev  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -       True var -


samtools: samtools
mapper: bowtie2
parser: ~t.v.schaik/mydata/modules/read-parsing/read_parser.py
