
outdir: /DATA/scratch/usr/c.leemans/projects/tagmap_hopping/results/cl20210504_mathias_landing_pad
input_dir: '/DATA/scratch/usr/c.leemans/data/forge/cl20210504_mathias_landing_pad'

## file_info contains information on the input files.
## it is a tab seperated file which requires the following columns in any order
# Sample_name - A unique identifier for the read pairs (so every ID occurs up to 2 times)
# structure - the structure of the constant part of the sequence (e.g. Sleeping Beauty transposon arm)
# genome - which genome version to use (has to be same name as in bowtie_index)
# mate - which mate of the paired-end sequence is used (R1 or R2)
# file - filename, if no input_dir is given a full path is required.
# construct_type - type of construct used, necessary to find back expected part on both side of insertion.
input_info: /DATA/scratch/usr/c.leemans/projects/tagmap_hopping/config/ME20210412_E1505_Mapping_LandingPads_files.tsv


## pairing_info contains information on which Sample_names of the input belong to the same construct.
## For samples from tagmentation on the hopping transposon there is also information on
## the samples or location info belonging to the sites of original intergration
pairing_info: '/DATA/scratch/usr/c.leemans/projects/tagmap_hopping/config/ME20210412_E1505_Mapping_LandingPads_pairing.tsv'

report_yaml: '/DATA/scratch/usr/c.leemans/projects/tagmap_hopping/src/scripts/pipeline_report.yaml'

mingap: 100

insert_ori: fwd

home_location:
    homology_arms:
        F1CBS_16:
            /DATA/scratch/usr/c.leemans/projects/tagmap_hopping/data/F1_CBS16_arms.fa
#     sanger:
#     coordinates:

home_sequence:
    F1CBS_16:
        /DATA/scratch/usr/c.leemans/projects/tagmap_hopping/data/F1CBS_16_2nd_file.fa


mapper_options: "--very-sensitive-local"
bowtie_index:
    mm10: "/DATA/scratch/usr/c.leemans/data/mm10/index/bowtie2/mm10_1-19_XYM"
    hg38: "/DATA/data/human/hg38/index/bowtie2/hg38_1-22_XYM"

ref_fasta:
    mm10: "/DATA/scratch/usr/c.leemans/data/mm10/genome/fasta/mm10_1-19_XYM.fa"
    hg38: "/DATA/scratch/usr/c.leemans/data/hg38/hg38_1-22_XYM.fa"

random_n: 10000

mast_minp:
    PB: 0.006
    SB: 0.08

add_to_refgenome:
    Tn5_plasmid:
        "/DATA/scratch/usr/c.leemans/projects/tagmap_hopping/data/His-SUMO3-Tn5.fa"


insertion_site:
    PB: TTAA
    SB: TA
    CRISPR: "-"

chrom_sizes:
    mm10: "/DATA/scratch/usr/c.leemans/data/mm10/mm10.chrom.sizes"
    hg38: "/DATA/scratch/usr/c.leemans/data/hg38/hg38.chrom.sizes"


## minimum for the maximum mapping quality of reads belonging to one putative insertion
min_max_mapq:
    paired: 2
    single: 10


max_pair_dist: 15000000

min_depth:
    paired: 0
    single: 3


structure:
    For_SB: |
        ID      5'             3' type                       req     second-read pos   keep-bases
        Tn5_constant      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   -  False var -
        SleepingBeaty_rc  -  TACAGTTGAAGTCGGAAGTTTACATACACCTT  const   -       False var 2
        SleepingBeaty      AGTGAGTTTAAATGTATTTGGCTAAGGTGTATGTAAACTTCCGACTTCAACTGTA -  const  present  True  var  2
        Tn5_constant_rc  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -        True var -
    Rev_SB: |
        ID      5'    3' type    req     second-read pos   keep-bases
        Tn5_constant      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   - False var -
        SleepingBeaty_rc  -  TACAGTTGAAGTCGGAAGTTTACATACACTTA  const   -       False var 2
        SleepingBeaty      AAACGAGTTTTAATGACTCCAACTTAAGTGTATGTAAACTTCCGACTTCAACTGTA  -  const   present True  var 2
        Tn5_constant_rc  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -       True var -
    For_SB_b: |
        ID      5'             3' type                       req     second-read pos   keep-bases
        Tn5_constant      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   -  False var -
        SleepingBeaty_rc  -  TACAGTTGAAGTCGGAAGTTTACATACACCTT  const   -       False var 2
        SleepingBeaty      AGTGAGTTTAAATGTATTTGGCTAAGGTGTATGTAAACTTCCGACTTCAACTGTA -  const  present  True  var  -
        junk               20                        - const present True - -
        Tn5_constant_rc  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -        True var -
    Rev_SB_b: |
        ID      5'    3' type    req     second-read pos   keep-bases
        Tn5_constant      CGTCGGCAGCGTCAGATGTGTATAAGAGACAG  -  const   - False var -
        SleepingBeaty_rc  -  TACAGTTGAAGTCGGAAGTTTACATACACTTA  const   -       False var 2
        SleepingBeaty      AAACGAGTTTTAATGACTCCAACTTAAGTGTATGTAAACTTCCGACTTCAACTGTA  -  const   present True  var 2
        junk               20                               - const present True - -
        Tn5_constant_rc  -  CTGTCTCTTATACACATCTGACGCTGCCGACG  const   -       True var -



hybrid:
    CAST-129S:
        CAST:
            /DATA/scratch/usr/c.leemans/data/GRCm38/species/CAST_EiJ.mgp.v5.snps.dbSNP142.20150105.filtered.vcf.gz
        129S:
            /DATA/scratch/usr/c.leemans/data/GRCm38/species/129S1_SvImJ.mgp.v5.snps.dbSNP142.20150105.filtered.vcf.gz

samtools: samtools
mapper: bowtie2
parser: ~t.v.schaik/mydata/modules/read-parsing/read_parser.py
